import Head from 'next/head'
import styles from '../styles/Home.module.css'
import SearchComponent from '../component/Search'



export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>MaGo SocialStore</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.png" />
      </Head>
    
      <main >
      <h3 className={styles.h1logo}><span>MaGo NetStore</span></h3> 
        <SearchComponent/>
      </main>
     
    </div>
    
  )
}


/* 
 export const getServerSideProps = function () { 
  const user = true

  if (!user) {
    return {
      redirect: {
        destination: '/login',
        permanent: false,
      },
    }
  }

  return {
    props: { user },
  }
} 
 */

